<?php
/**
 * @var Zend\Form\Form $form
 * @var ZfbUser\AuthenticationResult $authResult
 */

if (isset($authResult)) {
  if (!$authResult->isValid()) {
    echo "<h3>" . implode("<br/>", $authResult->getMessages()) . "</h3>";
  }
}

$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('zfbuser/authentication'));
$form->setAttribute('method', 'POST');

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
