<?php
/**
 * @var Zend\Form\Form $form
 * @var string $message
 */
?>
<h1>ZfbUser::add user</h1>

<?php if($message): ?>
<p><?=$message; ?></p>
<?php endif; ?>

<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('zfbuser/new-user'));
$form->setAttribute('method', 'POST');

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
